# Generated by Django 4.2.8 on 2023-12-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItemTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IMPORT', 'import'), ('EXPORT', 'export')], default=('IMPORT', 'import'), max_length=6)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productitem')),
            ],
        ),
    ]
